### ISSUE TITLE
netlib-java for performance

### ISSUE THREAD

**Issue by fommil** [mandubian/neurocat#1]
https://github.com/fommil/netlib-java

see the video from scalax14 contained in the readme for my complete argument for using it :wink:

**Comment by fommil** [comment]
oh, hold on, it's nd4j. yeah that's using netlib-java under the hood. carry on!

**Comment by mandubian** [comment]
Actually nd4j isn't really important to me, I just needed an array lib to demonstrate the concept but I could use any other lib too and will certainly try others... anyway, thks
